### PR TITLE
Added support for the AJAZZ AKP153 variant sold as the MiraBox HSV293S

### PR DESCRIPTION
**Pull request by czyz**
Added support for the MiraBox HSV293S, which seems to be a variant of the AKP153 with "FHOOU" emblazoned on the front.

### CODE REVIEW

**Comment by ninjadev64** [comment]
Why this company sells so many identical devices I will never understand.

**Comment by TheJebForge** [comment]
@czyz Will you be able to rebase your changes to new main and force push? Usually you can just create a new branch, cherry pick your commit to new one, delete old one and rename new one to old name. Force pushing from that point will reset the branch to be compatible with main

**Comment by danielk117** [comment]
I've resolved the merge conflicts. @TheJebForge you can use my https://github.com/danielk117/elgato-streamdeck/tree/streamdock293s or schould I create a new PR?

**Comment by czyz** [comment]
> @czyz Will you be able to rebase your changes to new main and force push? Usually you can just create a new branch, cherry pick your commit to new one, delete old one and rename new one to old name. Force pushing from that point will reset the branch to be compatible with main

I should be able to try that after this week. I don't have the cycles right now but I think I understand.

**Comment by danielk117** [comment]
see #22

**Comment by Snipees** [comment]
There is another variants too: https://github.com/streamduck-org/elgato-streamdeck/issues/23
Could you please add support for these ? Thanks

**Comment by danielk117** [comment]
> There is another variants too: https://github.com/streamduck-org/elgato-streamdeck/issues/23
> 
> Could you please add support for these ? Thanks

Seems to be the same vendor and product id. So it should be supported, if #21/#22 gets merged.

**Comment by ninjadev64** [comment]
Closing in favour of #22.

**Pull request closed without merging**
